#!/bin/bash
set -eu

cd $(dirname $0)

# We pretend filenames are unicode for two reasons: (1) because it exercises
# more code, and (2) this setting will detect accidental use of unicode strings
# for file/directory names when it should always be bytestrings.
export PRETEND_UNICODE_ARGS=1

failed=0

for test in t939*.sh; do
	./$test || failed=1
done
exit $failed
