#!/bin/bash

cd $(dirname $0)

# We pretend filenames are unicode for two reasons: (1) because it exercises
# more code, and (2) this setting will detect accidental use of unicode strings
# for file/directory names when it should always be bytestrings.
export PRETEND_UNICODE_ARGS=1

ls t939*.sh | xargs -n 1 bash
